<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>11</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="README.md" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="README.md" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CK.AppIdentity" Version="1.0.0--ci.2" />
    <PackageReference Include="CK.Globalization" Version="6.0.0--ci.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CK.Object.Processor\CK.Object.Processor.csproj" />
  </ItemGroup>
</Project>